// Constants
const TYPE_CLIENT_ACTION = "CLIENT_ACTION"

// Actions
const HELLO = "HELLO"
const WELCOME = "WELCOME"
const INIT_APP_PIPESTATE = "INIT_APP_PIPESTATE"
const UPDATE_APP_PIPESTATE = "UPDATE_APP_PIPESTATE"
const PIPE_MODIFY = "PIPE_MODIFY"
const PIPE_MODIFY_CLIENT = "PIPE_MODIFY_CLIENT"
const PEER_ACTION = "PEER_ACTION"


module.exports = {
  TYPE_CLIENT_ACTION,
  HELLO,
  WELCOME,
  INIT_APP_PIPESTATE,
  UPDATE_APP_PIPESTATE,
  PIPE_MODIFY,
  PIPE_MODIFY_CLIENT,
  PEER_ACTION
};
